[pytest]
# Это было добавлено в предыдущих уроках
python_files = *_tests.py test_*.py
python_classes = Test*
python_functions = test_*
# Регистрируем кастомные маркировки
markers =
    courses: Маркировка для страницы курсов.
    regression: Маркировка для регрессионных тестов.
    authorization: Маркировка для страницы авторизации.